Backport upstream commit aa54e50105836
Mark comparator call operator as const

llvm-svn: 290636

This fixes ToT build breakage

prebuilts/clang/host/linux-x86/clang-r563880c/include/c++/v1/__utility/lazy_synth_three_way_comparator.h:43:57:
error: no matching function for call to ob
ject of type 'const (anonymous namespace)::AliasPriorityComparator'
   43 |   _LIBCPP_HIDE_FROM_ABI bool __greater() const { return
__comp_(__rhs_, __lhs_); }
      |                                                         ^~~~~~~
...
external/llvm/utils/TableGen/AsmWriterEmitter.cpp:730:8: note: candidate
function not viable: 'this' argument has type 'const (anonymous
namespace)::Alias
PriorityComparator', but method is not marked const
  730 |   bool operator()(const ValueType &LHS, const ValueType &RHS) {
      |        ^

Test: build with clang-4376 from go/android-llvm-kokoro
Change-Id: Id2a03698e5a94a9f405a5910a4a788aa5be5fa5f