Suppress -Wunnecessary-virtual-specifier
With clang update, building code using llvm-project headers from older
version triggers the following build errors:

In file included from external/llvm/lib/Target/X86/X86FloatingPoint.cpp:27:
external/llvm/lib/Target/X86/X86InstrInfo.h:167:16: error: virtual method 'anchor' is inside a 'final' class and can never be overridden [-Werror,-Wunnecessary-virtual-specifier]
  167 |   virtual void anchor();

So suppress -Wunnecessary-virtual-specifier when llvm-project headers
are used.

Bug: 452729455
Test: build with clang update
Change-Id: I1a5467beeeaf1f0e59abe1d1ab5cfccbb8a5844b