Suppress -Wno-nonnull argument warning
We just add -Wno-nonnull to supress this warning.

external/llvm/lib/CodeGen/MachineVerifier.cpp:261:53: error: null passed
to a callee that requires a non-null argument [-Werror,-Wnonnull]
  261 |     MachineVerifierPass(const std::string &banner = nullptr)
      |                                                     ^~~~~~~
1 error generated.

Bug: 430598176
Test: m && presubmit

Change-Id: I7051d30e7a7b4f4e3dd34d3f4a378d533d279058