Backport upstream commit 0a9eb89
Give comparator const call operator
llvm-svn: 292043

This fixes ToT build breakage

prebuilts/clang/host/linux-x86/clang-r563880c/include/c++/v1/__utility/lazy_synth_three_way_comparator.h:43:57: error: no matching function for call to object of type 'const ScheduleDataCompare'
   43 |   _LIBCPP_HIDE_FROM_ABI bool __greater() const { return
   __comp_(__rhs_, __lhs_); }
...
external/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp:3148:10: note: candidate function not viable: 'this' argument has type 'const ScheduleDataCompare
', but method is not marked const
 3148 |     bool operator()(ScheduleData *SD1, ScheduleData *SD2) {
       |          ^

Test: build with clang-4376 from go/android-llvm-kokoro
Change-Id: I6b69bb55decb52495276d959e977f2b3633a07b7